### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by jgardner-qha** [erlwes/InactiveWipe#3]
When I tried installing the script using Install-Script, I got a parse error.

To resolve that, I downloaded the script directly from GitHub, but then I had to remove the ErrorMessage parameters from the ValidateScript functions on lines 53 and 56 before it would run. I'm not sure if it's due to my version of PowerShell.

Then, the script ran nicely. I was able to open a list of users and copy them into Excel, but once I closed the list, I could no longer do anything with the GUI; it became completely unresponsive. I had to use Task Manager to forcefully close PowerShell before I could run it again.

That being said, I was able to hobble through and remove many inactive guest users! My user list looks so much better now; your work on this script is very much appreciated!

$PSVersionTable

Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
PSVersion                      5.1.22621.3880                                                                                                                                                 
PSEdition                      Desktop                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   10.0.22621.3880                                                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1

**Comment by jgardner-qha** [comment]
For what it's worth, using a newer version of Powershell resolves the parse error, but I can no longer open the actual lists (nothing happens when clicking on the icon).

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.4.4
PSEdition                      Core
GitCommitId                    7.4.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by erlwes** [comment]
Thank you for letting me know 🙏
I run my enviroment in PowerShell 7 only, and did not think of testing it in 5.1.

I have now ...
1. Removed the ErrorMessage-parameter from the validate script part (not supported in 5.1)
2. Removed the banner if PowerShell-version is not 7 (-gt 5)
3. Changed the emoji insights icon, so it renders in PS5.

**Comment by erlwes** [comment]
The changes are commited to PowerShell Gallery, and to git.

`Update-Script InactiveWipe` should resolve your problems.

**Comment by jgardner-qha** [comment]
I greatly appreciate your efforts on this, and the incredibly quick response. Excellent work, thank you!

Yes, it now works perfectly in my environment.
