### ISSUE TITLE
You called a value on a null-valued expression

### ISSUE THREAD

**Issue by myatix** [erlwes/InactiveWipe#4]
I am getting the following error when running this tool...

     | You cannot call a method on a null-valued expression.
InvalidOperation: C:\Users\XXX\OneDrive - H. Lundbeck A S\Documents\VS Code Repo\InactiveWipe\InactiveWipe.ps1:297:9
Line |
 297 |          $UserObj = [pscustomobject]@{
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

The error repeats 10 times before returning the final result totals.

**Comment by myatix** [comment]
In addition to the above I am also recieveing the following error when I try to download the report. (Click the icon!)

Out-GridView: C:\Users\XXX\OneDrive - H. Lundbeck A S\Documents\VS Code Repo\InactiveWipe\InactiveWipe.ps1:469:35
Line |
 469 |  … rSignedIn | Out-GridView -Title "Never logged in $($UserType.ToLower( …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception has been thrown by the target of an invocation.

**Comment by erlwes** [comment]
Hello - thank you for letting me know.

Beside the error-messages, does the script work? Do you get users from the Graph request?

Therory, based on the partial error-message:
I need to handle cases where one or more of the categories has 0 results.

Say that there are 0 users that has never logged in, then this will produce an empty variable, that can cause error-messages if tried to do match upon, to make graphs or calculate percentages etc.

Are you running PowerShell 5 or 7? Any screenshots or complete error-messages? 🙏

**Comment by erlwes** [comment]
Hello

I believe I have re-produced the error. I'm guessing you used the experimental "memberMode" parameter?
The Issue should be fixed now if you re-download from GitHub or PowerShell-Gallery (Install-Script).

**Comment by myatix** [comment]
Not in front of my machine right now!Is there a way to turn on verbose logs or similar that I can send you.Ya we have 6000 guest accounts so lots of variables that could cause the errors I would imagine. But a really great start to a very useful tool Also could not see a simple way to export the CSV?Great work so far!On 20 Aug 2024, at 21.29, Erlend ***@***.***> wrote:﻿
Hello - thank you for letting me know.
Beside the error-messages, does the script work? Do you get users from the Graph request?
Therory, based on the partial error-message:
I need to handle cases where one or more of the categories has 0 results.
Say that there are 0 users that has never logged in, then this will produce an empty variable, that can cause error-messages if tried to do match upon, to make graphs or calculate percentages etc.
Are you running PowerShell 5 or 7? Any screenshots or complete error-messages? 🙏

**Comment by erlwes** [comment]
Hello,

Wow - that is a lot of guests. Let me know if the errors are gone. I was able to reproduce the exact same errors. It happened when it got to users that had no email-address attribute.

Export CSV
For now the UPN of selected users a copied to clipboard when you hit the "OK" button in the "Gridview".
This list of UPNs would then have to be used in another script, or in the "bulk operations" via. Entra ID portal, as explained at the bottom of the GitHub page (Readme.md).

You can also to ctrl+A in the gridview, and paste directly to Excel. You loose the headers, but all the content copies nicely.

I will consider making a save to CSV button :)

**Comment by myatix** [comment]
Thanks for resolving the bugs! :)It has fixed the issue we had… It would be nice if there was a way to export the results with the column headers. The current solution doesn’t seem to allow for this. I think I would rather have an export to CSV instead of the grid view.Keep up the great work!On 21 Aug 2024, at 23.24, Erlend ***@***.***> wrote:﻿
Hello,
Wow - that is a lot of guests. Let me know if the errors are gone. I was able to reproduce the exact same errors. It happened when it got to users that had no email-address attribute.
Export CSV
For now the UPN of selected users a copied to clipboard when you hit the "OK" button in the "Gridview".
This list of UPNs would then have to be used in another script, or in the "bulk operations" via. Entra ID portal, as explained at the bottom of the GitHub page (Readme.md).
You can also to ctrl+A in the gridview, and paste directly to Excel. You loose the headers, but all the content copies nicely.
I will consider making a save to CSV button :)

**Comment by erlwes** [comment]
@myatix  - The script is now updated with save to CSV-buttons :)
